[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.22"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
]
via_ir = true
optimizer = true
ffi = true
