[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.22"
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "foundry-huff/=lib/foundry-huff/src/"
]
via_ir = true
optimizer = true
ffi = true
